env_config:
  res_gen_type: random               
  max_cycles: 10000
  agents_produce_resources: true
  world_bound: 4
  eating_distance: 0.5
  num_agents: 20
  visibility: 2
  sigma: 0.2
  model_sigma: 0.02
  num_resources: 120
  recov_time: 50
  agent_lifetime: 125
  
  use_energy_resource: False
  move_cost: 5
  prod_cost: 150
  reprod_cost: 150
  idle_cost: 2
  max_energy: 300
  attack_action: True
  eat_action: True
  novelty_buffer_size: 10
  novelty_threshold: 1