env_config:
  res_gen_type: random               
  max_cycles: 1000000
  world_bound: 8
  eating_distance: 0.3
  visibility: 2
  sigma: 0.05
  model_sigma: 0.05
  wrap_around: False
  select_by_distance: 3
  energy_distance_type: "exp"
  step_reward: 5
  repr_reward: 1000
  attack_action: True
  eat_action: True
  produce_res_action: True
  waste_lifetime: 2000


  num_resources: 100
  recov_time: 50
  max_n_agents: 5
  move_cost: 5
  max_energy: 4500
  prod_cost: 250
  reprod_cost: 1505
  idle_cost: 2
  attack_cost: 50

  energy_coef: 2
  consumption_threshold: 1.35
  species_eating_cutoff: 1.8
  seed_val: 2


