env_config:
  res_gen_type: random               
  max_cycles: 1000000
  world_bound: 6
  eating_distance: 0.4
  num_agents: 1
  visibility: 2
  sigma: 0.1
  model_sigma: 0.05
  agent_lifetime: 60
  obs_size: 8
  wrap_around: False
  seed_val: 0
  select_by_distance: 10
  energy_distance_type: "exp"

  num_resources: 50
  recov_time: 100
  max_n_agents: 1
  use_energy_resource: False
  move_cost: 5
  max_energy: 4500
  prod_cost: 250
  reprod_cost: 1505
  idle_cost: 2
  attack_cost: 50
  attack_action: True
  eat_action: True
  produce_res_action: True
  novelty_buffer_size: 10
  novelty_threshold: 1
