env_config:
  res_gen_type: random               
  max_cycles: 10000
  agents_produce_resources: true
  world_bound: 4
  eating_distance: 0.5
  num_agents: 1
  visibility: 2
  sigma: 0.2
  model_sigma: 0.002
  num_resources: 50
  recov_time: 50
  agent_lifetime: 125

  
  use_energy_resource: False
  move_cost: 10
  prod_cost: 250
  reprod_cost: 250
  idle_cost: 5
  max_energy: 500
  attack_action: True
  consume_action: True
